# Generated by Django 5.0.2 on 2024-02-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="club",
            field=models.ManyToManyField(to="employee.club", verbose_name="部活"),
        ),
    ]
